---
title: "A latex cheatsheet for biologists"
description: |
  A short description of the post.
author: Nathan L. Brouwer
date: 2022-05-07
output:
  distill::distill_article:
    self_contained: false
draft: false
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Greek symbols

```{r}
df <- data.frame(Symbol = c(  "\\(\\lambda\\)", "\\(\\rho\\)",
                              "\\(\\delta\\)","\\(\\Delta\\)"),
                 Name   = c(  "lambda",       "rho", "delta","Delta"),
                 LaTex  = c(    "\\lambda", "\\rho","\\delta","\\Delta"))
```


```{r}
pander::pander(df)

```



## Formatting

```{r}
              #what                 latex           example
exponent  <- c("Exponent",           "e^x",         "\\(e^x\\)")
subcript1 <- c("Subscript-simple",   "N_t",         "\\(N_t\\)")
subcript2 <- c("Subscript-complex",  "N_{t+1}",     "\\(N_{t+1}\\)")
fraction  <- c("Fraction",           "\frac{x}{y}", "") # \\(\frac{x}{y}\\)
df <- rbind(exponent, subcript1,subcript2,fraction)
```

\(\frac{x}{y}\)

```{r}
pander::pander(df[,])

```



