---
title: "Scatterplot case study: Ecological succession in Mexico"
description: |
  A short description of the post.
author: Nathan L. Brouwer
date: 2022-05-05
output:
  distill::distill_article:
    self_contained: false
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


Data were extracted from Figure 2a of [Lebrija-Trejos et al. (2008)](https://onlinelibrary.wiley.com/doi/full/10.1111/j.1744-7429.2008.00398.x) using [metaDigitise](https://cran.r-project.org/web/packages/metaDigitise/vignettes/metaDigitise.html).


```{r}
Species <- c(17,14, 16 ,33, 37 ,37 ,29 ,39 ,49 ,48 ,45 ,55)
Year <- c(1, 3, 5, 10, 14, 18, 22, 27, 32, 37, 40, 45)
dat <- data.frame(Species, Year)
plot(Species ~ Year, data = dat, pch = 15, cex = 2,
     xlab = "", ylab = "", col = "darkgreen")
m <- lm(Species ~ Year, data = dat)
abline(m)
abline(v = 43, lty = 2)
mtext(text = "Year", line = 3, side = 1, cex = 2)
mtext(text = "Species", line = 2.5, side = 2, cex = 2)
mtext(text = "              Young forest", line = 1, side = 3, cex = 1,at = 1)
mtext(text = "Old forest", line = 1, side = 3, cex = 1,adj = 1)
coef(m)
legend("topleft", legend = "Species = 17.4 + 0.82*Year")
```


## References

[Lebrija-Trejos et al.](https://onlinelibrary.wiley.com/doi/full/10.1111/j.1744-7429.2008.00398.x)  Successional Change and Resilience of a Very Dry Tropical Deciduous Forest Following Shifting Agriculture.  Biotropica 40: 422–431.  10.1111/j.1744-7429.2008.00398.x.
