---
title: "Scatterplot case study"
description: |
  A short description of the post.
author: Nathan L. Brouwer
date: 2022-05-05
categories:
  - base R
  - scatterplots
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


Data were taken from Table 3 of [Keeping et al 2018](https://www.sciencedirect.com/science/article/pii/S0006320717317780).


[Keeping et al 2018](https://www.sciencedirect.com/science/article/pii/S0006320717317780).  Can trackers count free-ranging wildlife as effectively and efficiently as conventional aerial survey and distance sampling? Implications for citizen science in the Kalahari, Botswana.  Biological Conservation 223: 156-169.  https://doi.org/10.1016/j.biocon.2018.04.027






```{r}
D.aerial <- c(5.01, 1.76, 0.61, 0.29, 0.53, 0.88, 0.07, 0.06, 0.2)
D.track <- c(2.12, 1.94, 0.62, 0.14, 0.58, 0.24, 0.21, NA, NA)

plot(D.aerial ~ D.track, 
     xlab = "Density from data collected by traditional trackers", 
     ylab = "Density from aerial survey",
     main = "Density estimations of 7 species by \nlocal trackers vs. ecologists in planes",
     pch = 12:19)
abline(lm(D.aerial ~ D.track))
coef(lm(D.aerial ~ D.track))
```

